Repository vsouza/awesome-ios, pull requests merged in 2018-12, with the labels that each got.

#2692 Split Injection section into two
  README.md
Labels: waiting manager

#2691 Added VIPER Module Template to Architecture Patterns
  README.md
Labels: needs classification

#2694 feat: add SwiftLinter
  README.md
Labels: question

#2712 Added MSFlightMapView
  README.md
Labels: waiting
